import{A as S,a as I,i as $,S as N,N as q,K as A}from"./assets/vendor-DR3QWmmZ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const w=document.getElementById("btn-header");document.getElementById("header-mob-span");let h=!1;w.addEventListener("click",()=>{h=!h;const e=document.documentElement;h?(w.classList.add("right"),e.style.setProperty("--white","#1E2023"),e.style.setProperty("--black","#F0F0F0"),e.style.setProperty("--accent-green","#14C57C"),e.style.setProperty("--light-grey","#2A2D32"),e.style.setProperty("--light-accent","#204136"),e.style.setProperty("--hover-grey","#3B3F45")):(w.classList.remove("right"),e.style.setProperty("--white","#F0F0F0"),e.style.setProperty("--black","#292929"),e.style.setProperty("--accent-green","#00B068"),e.style.setProperty("--light-grey","#E4E5E6"),e.style.setProperty("--light-accent","#BCDFD1"),e.style.setProperty("--hover-grey","#BBBBBB"))});const c={openModalBtn:document.querySelectorAll(".js-open-menu"),closeModalBtn:document.querySelector(".js-close-menu"),modal:document.querySelector(".js-menu-container"),modalLinks:document.querySelectorAll(".mob-nav-tag")};c.openModalBtn.forEach(e=>{e.addEventListener("click",j)});c.closeModalBtn.addEventListener("click",j);c.modal.addEventListener("click",F);function F(e){e.target===e.currentTarget&&c.modal.classList.add("is-active")}function j(){c.modal.classList.toggle("is-active"),document.body.classList.toggle("no-scroll")}c.modalLinks.forEach(e=>{e.addEventListener("click",()=>{c.modal.classList.remove("is-active"),document.body.classList.remove("no-scroll")})});const O=10,k=3,u=[],T=["power pulse webservice","mimino website","vyshyvanka vibes Landing Page","green harvest online store","wallet webservice","chego jewelry website","energy flow webservice","fruitbox online store","English excellence webservice","starlight studio landing page"],L=document.querySelector("button.projects-more"),D=document.querySelector("ul.projects-list"),V=()=>{const e=document.querySelectorAll("ul.projects-list li");e[e.length-1].scrollIntoView({behavior:"smooth"})},z=()=>{L.style.display="none"},J=()=>{L.style.display="block"},H=e=>{for(let o=0;o<e;o++){const n=T[o],s=o+1;u.push({idx:s,name:n,visible:!1})}},K=e=>{D.innerHTML+=e.map(o=>{const{idx:n,name:s}=o,t=u.findIndex(r=>r.idx===n);return u[t].visible=!0,`
            <li>
                <img class="project-img" 
                    srcset="/img/projects${n}.jpg 1x, /img/projects${n}_xx.jpg 2x"
                    src="/img/projects${n}.jpg"
                    alt="${s}"
                    loading="lazy">
                <span class="projects-stack">React, JavaScript, Node JS, Git</span>
                <div class="projects-box">
                    <span class="projects-name">${s}</span>
                    <span class="projects-visit">
                        <a class="projects-link" href="#">
                            visit
                            <svg class="projects-icon">
                                <use href="/img/icon.svg#icon-projects-icon"></use>
                            </svg>
                        </a>
                    </span>
                </div>
            </li>
        `}).join("")},B=(e,o)=>{const n=u.filter(t=>t.visible===!1),s=n.length;if(s){J();const t=s>=e?e:s;K(n.slice(0,t)),o&&V(),s<=e&&z()}},R=()=>{B(k,!0)};H(O);B(k,!1);L.addEventListener("click",R);new S(".accordion-container",{openOnInit:[0]});const M=document.querySelector(".swiper-wrapper"),G=document.querySelector(".button-wrapper");function Z(e){const o=e.map(({author:n,avatar_url:s,review:t,_id:r})=>r===5?`<li class="swiper-slide">
					<p class="reviews-text">${t.slice(0,-31)}</p>
					<div class="card-wrapper">
						<img class="reviews-icon" src="${s}" alt="${n}">
						<h2 class="reviews-author">${n}</h2>
					</div>
				</li>`:`<li class="swiper-slide">
					<p class="reviews-text">${t}</p>
					<div class="card-wrapper">
						<img class="reviews-icon" src="${s}" alt="${n}">
						<h2 class="reviews-author">${n}</h2>
					</div>
				</li>`).join("");M.innerHTML=o,G.classList.remove("visually-hidden")}function Q(){const e=`<li class="not-found swiper-slide">
	<p class="not-found-text">Not found!</p>
</li><li class="not-found swiper-slide">
	<p class="not-found-text">Not found!</p>
</li>`;M.innerHTML=e}async function U(e){try{const{data:o}=await I.get("https://portfolio-js.b.goit.study/api/reviews");Z(o)}catch(o){Q(),$.error({position:"topRight",message:o.message})}}U();new N(".swiper",{modules:[q,A],direction:"horizontal",navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0},slidesPerView:1,spaceBetween:32,breakpoints:{1280:{slidesPerView:2}}});document.addEventListener("DOMContentLoaded",function(){const e=document.getElementById("work-together-form"),o=document.getElementById("modal-backdrop"),n=document.getElementById("modal-close-btn"),s=document.getElementById("modal-title"),t=document.getElementById("modal-message"),r=document.getElementById("email"),i=document.getElementById("user-comment"),y=document.getElementById("email-error"),p=document.getElementById("message-error"),g=document.querySelector(".work-together-form-input-valid");function f(a,d){s.textContent=a,t.textContent=d,o.classList.add("active")}function v(){o.classList.remove("active")}function E(a){return/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(a)}function P(){y.textContent="",p.textContent=""}r.addEventListener("input",()=>{P(),E(r.value.trim())?(r.classList.remove("error"),r.classList.add("valid"),g.style.display="inline"):(r.classList.add("error"),y.textContent="Invalid email, try again",g.style.display="none")}),i.addEventListener("input",()=>{i.value.trim()!==""?(i.classList.remove("error"),i.classList.add("valid"),p.textContent=""):(i.classList.remove("valid"),i.classList.add("error"),p.textContent="Message cannot be empty")}),e.addEventListener("submit",async a=>{a.preventDefault();const d=r.value.trim(),b=i.value.trim();if(!E(d)){y.textContent="Please enter a valid email address.";return}if(!b){p.textContent="Message cannot be empty.";return}var C={email:d,comment:b};const x=JSON.stringify(C);console.log(x);try{const l=await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:x});if(l.ok){const m=await l.json();f(s.textContent,t.textContent||"Message sent successfully!"),e.reset(),g.style.display="none"}else{const m=await l.json();console.error("Error response:",m),s.textContent="Error",s.style.color="red",f(s.textContent,m.message||"Unexpected error, please try again.")}}catch(l){const m=l.message;console.error("Network Error:",m),s.textContent="Network Error",s.style.color="red",f(s.textContent,`Network error: ${l.message}`)}}),n.addEventListener("click",v),o.addEventListener("click",a=>{a.target===o&&v()}),document.addEventListener("keydown",a=>{a.key==="Escape"&&v()})});
//# sourceMappingURL=index.js.map
